include: 
  - ".github/**/*"
  
skip_render: 
  - ".github/**/*"
  
  
deploy:
  type: git
  ignore_hidden: false # 添加这个属性值为false
  repo: 
    gitee: git@gitee.com:你的Gitee仓库.git,要使用的分支名
    github: git@github.com:你的Github仓库.git,要使用的分支名
    # 可以先提交Gitee然后再提交Github，也就是把这个Gitee的地址放在前面。这样保证Gitee的站点内容能在Github开始动作之前完成提交。
